hypriot_lirc:
  build: .
  ports: 
    - "8002:8080"
    - "9001:9001"
  volumes:
    - "/opt/projects/hypriot-lirc/conf:/etc/lirc/"
    - "/sys/bus/w1/devices:/sys/bus/w1/devices"
  devices:
    - "/dev/mem:/dev/mem"
    - "/dev/lirc0:/dev/lirc0"
